### ISSUE TITLE
Winget package

### ISSUE THREAD

**Issue by majkinetor** [1Remote/1Remote#402]
I should do a winget package (and get oportunity to learn more about it). One of the reasons is that chocolatey package for 1RM is submited a month ago and still not approved (and Chocolatey is becoming more and more hostale toward FOSS users).

**Comment by majkinetor** [comment]
Unfortunatelly, winget doesn't support apps that do not have installers. So installer needs to be done to support it. 

The supported installers are listed [here](https://learn.microsoft.com/en-us/windows/package-manager/winget/#supported-installer-formats). 

ZIP installerrs are added recently, but they are mostly single files. I found one that is larger archive - [yazu](https://github.com/microsoft/winget-pkgs/blob/c7caa8eed1857df410bf88e0159a73c960382842/manifests/y/YuzuEmu/Yuzu/Mainline/1287/YuzuEmu.Yuzu.Mainline.installer.yaml). This means winget will simply unpack archive to default or desired location.

Choco package has a PowerShell script that can do anything, which I used to restart running process and create desktop icon. This will not be possible here. Neverthless, I am happy its now possible, so I will give it a try and see how it goes. If nothing else, we will make installer. 

/cc @VShawn .

**Comment by VShawn** [comment]
appx and msix can be built by the installer project in the solution, but i didn't figure out how to build them by a script.

**Comment by majkinetor** [comment]
Here is the [zip spec](https://github.com/microsoft/winget-cli/blob/master/doc/specs/%23140%20-%20ZIP%20Support.md)

**Comment by majkinetor** [comment]
Progress so far.

winget doesn't support dependencies yet so one most install manually dotnet desktop runtime:

```
winget install Microsoft.DotNet.DesktopRuntime.6  --accept-source-agreements --accept-package-agreements
```

After trying my manifest it extracted it in Temp folder but failed to open it. On double click it offers MS Store, but if run from command line it executes:

![Animation](https://github.com/1Remote/1Remote/assets/85767/4a372c4f-b2b4-4c37-b437-33de635c48e1)

Anyway, this installer manifest passes:

```
PackageIdentifier: 1Remote.1Remote
PackageVersion: 1.0.0.3
Installers:
- InstallerUrl: https://github.com/1Remote/1Remote/releases/download/Nightly/1Remote-1.0.0.0-beta.03-net6-x64-nightly-20230513-3ba04d.zip
  Architecture: x64
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: 1Remote.exe
  InstallerSha256: EF3508A3FFEF1627655ACE920AC5DDD2A80ABEFE2A2B6547430C2145EDCFB23D
ManifestType: installer
ManifestVersion: 1.4.0
```

Once published, one installs this using the following command:

```
winget install Microsoft.DotNet.DesktopRuntime.6  --accept-source-agreements --accept-package-agreements
winget install 1Remote --location c:\tools\1Remote
```

Without location, default location is `%LOCALAPPDATA%\Microsoft\WinGet\Packages\1Remote.1Remote__DefaultSource` which is amazingly bad. Symbolic link is created tho at `%LOCALAPPDATA%\Microsoft\WinGet\Links\1Remote.exe` which if run fails because SQLite dll can't be found :)

So, to recap:

1. Location must be used
2. Desktop runtime will be probably automatically installed somewhere in the future when dependencies do work (currently mockup is available as winget feature flag)
3. If we change `portable` to `exe` winget calls 1Remote.exe after extraction, and it could pass silent install parameters that we could use to create desktop icon and/or run the app in the background.
4. MS Store search wont happen outside the Sandbox, I tested on my local machine

![Animation](https://github.com/1Remote/1Remote/assets/85767/4ac82e65-45bd-48b7-87a9-7462eb82492a)
